### ISSUE TITLE
티켓 환불/영수증 대응

### ISSUE THREAD

**Issue by scari** [pythonkr/pyconkr-2015#104]
티켓을 구매했지만 회사에서 스폰서 티켓을 제공받은 경우에 대해서 @darjeeling님이 환불을 해준게 있습니다. 같은 사유에 대해서 환불 요청이 들어오면 처리를 해줘야 합니다.

영수증 요구가 많이 들어왔고 다음 주(8/24~) 부터 처리해주겠다고 답장을 했으니 약속을 지켜야 합니다.

**Comment by OuO** [comment]
추가로 진행될 사항이 없는 것으로 알고 있습니다. Ticket close 합니다.
