### ISSUE TITLE
OLC 오디오 별도 녹음 확인하기

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2015#105]

**Comment by tebica** [comment]
contact 남지현 책임연구원

**Comment by darjeeling** [comment]
어떤건인지 알수 있을까요?

**Comment by tebica** [comment]
제가 이번에 회사 비디오를 찍으면서 한 경험에 의하면, 멀리서 카메라에서 녹음하는 것보다 직접 마이크를 차고 녹음하여 카메라에 입력을 넣어주는게 훨씬 깔끔한 소리가 들렸습니다. 마이크는 하루 대여비 1만원 정도 하구요.
OLC에서 무선마이크로 녹음이 가능한지 확인해보고 안되면 Pycon 예산으로 마이크를 빌려서 사용해달라고 하는게 어떤가 합니다.
마이크 : http://www.slrrent.com/acc_recording.php
마이크녹음 결과물 : https://realm.wistia.com/medias/ulj0s876se
작년 파이콘 소리 : https://www.youtube.com/watch?v=E4bF3tPxeDE

**Comment by darjeeling** [comment]
지난번에도 마이크로 녹음했던거 같은데.. ㅠㅠ

확인부탁드립니다.

감사합니니다.

**Comment by tebica** [comment]
남지현 책임님 휴가중.. 전화 받으신분이 확인해서 알려주신다고 합니다.

**Comment by OuO** [comment]
OLC 녹화에 대해서는 마감합니다.

모두 수고하셨습니다.
