### ISSUE TITLE
PYCON US와 APAC 탐사단.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#11]

**Comment by OuO** [comment]
PyCon US 참석은
- @darjeeling 
- @scari 
- me

까지 총 3명입니다. #16 내용을 참고하시면 되겠습니다.

**Comment by OuO** [comment]
PyCon APAC 참석자는
- @lexifdev 
- @miyunim 
- @Bloodevil 
- @darjeeling 

(위 명단은 변경 될 수 있습니다.)

**Comment by Bloodevil** [comment]
PyCon APAC 참석으로 새로운 이슈를 만들고 이 이슈는 닫습니다.
현재 PyCon US 참가자들은 모두 갔습니다.
