### ISSUE TITLE
event.pycon.kr 도메인 활성화

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#14]
빨리 해주시죠.

**Comment by Bloodevil** [comment]
활성화는 되었으니 클로즈 합니다. 누군가 걸어주세요. 2월땐 될꺼라 믿..믿...

**Comment by lqez** [comment]
www.pycon.kr 만 활성화했고, event / seminar 는 작업하지 못했습니다.
2014-10 세미나 때는 seminar.pycon.kr 로 도메인을 잡아서 작업했는데, 사실 seminar.python.or.kr 이나 event.python.or.kr 이 맞다고 봅니다. 하지만 없는 것 보다는 있는게 훨씬 의미가 있으니, @Bloodevil 님께서 event 와 seminar 중에서 2차 도메인 선택해주시면 한 쪽으로 301 시키도록 하겠습니다.

**Comment by Bloodevil** [comment]
event로 하죠. github repo 따라서 통일 하는 거스로. ^ㅁ^

**Comment by lqez** [comment]
그럼 우선 event.pycon.kr/<event_id> 로 작업하고, python.or.kr 을 획득하면 그 쪽을 메인 도메인으로 하겠습니다.
seminar.pycon.kr 은 event.pycon.kr 로 301 시키겠습니다.
