### ISSUE TITLE
Submit PSF grant proposal

### ISSUE THREAD

**Issue by invisibleroads** [pythonkr/pyconkr-2015#15]
Hi 배권한, 김영근, 박민우 and others,

[It was great meeting you yesterday at the Korean Python Users Group](http://bloodevil.com/pages/minicon_2014_12.html).  I was happy to witness a packed auditorium as well as presentations on advanced topics such as IPython extensions.  I was also impressed that your team managed to bootstrap PyCon Korea 2014 on your own through regional sponsors.  Thank you also for letting me participate in the PyCon Korea 2015 organizers kickoff session, where I counted seven organizers (self excluded).

In order to submit a PSF grant proposal, I will need your help with the following questions.

1. What is the objective of the grant?  When do you need the funds?
2. How much funding do you need?  What is the cost breakdown?
3. Who will be the beneficiaries?  What is the estimated number of attendees?
4. What is the timeline of status updates?
5. How do you want to receive the funds?

Please see the [PSF Grants Program](https://www.python.org/psf/grants/) for more details.

> A typical conference grant size is USD 10 per attendee,
> with exceptions for smaller conferences that need extra financial assistance.

**Comment by invisibleroads** [comment]
I recommend submitting the proposal before February.

**Comment by darjeeling** [comment]
@invisibleroads thanks! I start this issue from at the end of this week.

**Comment by tebica** [comment]
@darjeeling I will help answering this questions in English. Please ping me anytime if you need any time of help from me. When are we gonna discuss this?

**Comment by Bloodevil** [comment]
we should discuss before February. please do discuss (or determine meeting date)

**Comment by Bloodevil** [comment]
@darjeeling  이거 어케되고 있나요 업데이트 부탁드리고 이슈 필요없으면 클로즈 합니다. 파이썬 달력에 등록하는것과 같이 하실꺼면 이슈에 dup 표시하고 내용 합쳐주세요.

**Comment by tebica** [comment]
@darjeeling 일단 제가 영어로 초안을 만들어 보겠습니다.
- 우리가 돈이 얼마나 필요한가 -> 요건 답을 어떻게?
- 돈을 어떻게 받기를 원하는가? ->우리 법인통장 만들 예정인가요?

**Comment by darjeeling** [comment]
@tebica  
* 얼마나 필요한가는 800 명 규모의 행사를 예상중이므로 인당 * 10$ 정도면 될꺼 같습니다. ( 양일인데다가.. ) 
* 아직은 법인이 없으니까 개인 paypal 이나 저의 통장이면 될듯하네요. 일단은요..

**Comment by tebica** [comment]
@darjeeling 네. $8,000 으로 개인 통장으로 일단 작성하겠습니다.

**Comment by darjeeling** [comment]
@tebica 
* 기존의 coc 링크가 필요할꺼 같습니다.
* http://www.pycon.kr/2014/about/coc/

**Comment by tebica** [comment]
@darjeeling Draft 완성하였습니다. 리뷰 부탁드립니다.
예산도 일단 현재 버전으로 영문화 하였습니다.

**Comment by tebica** [comment]
@darjeeling 
Plan 1 : $8,000 fund.
Plan 2 : Recommend 3~4 English Python speakers and support that cost (flight, travel etc.)

**Comment by tebica** [comment]
PSF grant 문서는.. 다양한 오픈소스 fund grant 문서를 작성한 경험이 많은 저랑 같이 일한 적이 많은  Tim Anglade의 도움으로 문서자체를 업데이트 하고 있습니다.

**Comment by darjeeling** [comment]
:+1:

**Comment by tebica** [comment]
@invisibleroads Hello Roy,
Korea team's PSF grant submission is a bit delayed. we are trying to finish this by Feb 20th. Do you think this schedule is ok?

**Comment by invisibleroads** [comment]
If you make an initial translation into English, then I can help correct grammar and such.

I'm not an authorized representative for the PSF, so I can't guarantee anything about recommended deadlines.  The best I can say is that the sooner you submit the request, the sooner the committee will review it.

**Comment by invisibleroads** [comment]
@tebica 
Is there a draft that I should proofread?

**Comment by tebica** [comment]
@invisibleroads Can you please review below doc? if you have any permission issue, please let me know
https://docs.google.com/document/d/1p6EOvQaQ6nN8yiNuFL9KXIXVudhf0_cbQTfxMrs8g5A/edit#

**Comment by invisibleroads** [comment]
@tebica, I finished editing the draft.  Overall, it is pretty good and it looks ready to submit.  I restricted the editing permissions just in case.

**Comment by tebica** [comment]
@invisibleroads Thank you!
@darjeeling We are ready to send this!

**Comment by darjeeling** [comment]
@invisibleroads @tebica  thanks for reviewing!
I sent it

**Comment by invisibleroads** [comment]
Cool!
