### ISSUE TITLE
web server 이전 

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#20]
11:53 AM darjeeling 음 전 크리스마스때.. pycon.kr 을 네이버 제공 써버로 옴기겠습니다.
11:53 AM server 관리용 key 도 받아서.. 넣을께요. 

=======================================
할일
- naver 제공서버 환경 ip와 알아야할 정보들 이슈에 달아놓기
- pycon.kr 웹서버 이전
- 하면서 #14 이슈도 같이 끝내주세요.
- key 받으면 slack이나 google docs나 비슷한것(?) 으로 공유 하기.

**Comment by darjeeling** [comment]
https://github.com/pythonkr/pyconkr-environment

의 admin_ssh_keys 에 본인의 ssh pub key 를 넣어주세요.

**Comment by lqez** [comment]
저는 등록했습니다.

**Comment by Bloodevil** [comment]
저도 등록했습니다. 
서버 옮기셨으면 close 해주세요.

**Comment by Bloodevil** [comment]
클로즈 해달라고....
