### ISSUE TITLE
장소 후보 선정 및 예약, 견적 요청 메일 보내기.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#22]
https://docs.google.com/spreadsheets/d/1SzkOiTb4iH0adUoTItXYywmoviCLpi50EA82stQG7X0/edit#gid=0

장소선정 후보와 메일 보낼 후보들.

**Comment by Bloodevil** [comment]
CFP 작성되었으니 토요일에 후보 골라서 쭉 뿌려봅시다. pycon 공식 메일로 뿌리도록 합시다.  토요일 당일날 보내고 클로즈 합니다. 이후 메일 오는 것을 보고 새로 이슈레이징 하도록 하겠습니다.

**Comment by darjeeling** [comment]
CFP 와 장소는 별개의 것아닌가요?

**Comment by Bloodevil** [comment]
문서가 있어야 뭔가 보내죠. CFP 는 아니지만 뭔가 비슷한 썸씽 라이크 뎃 이 필요함. 저번에 뿌린건 cfp 초안으로 조금 수정해서 보냈습니다.

**Comment by Bloodevil** [comment]
CFP 는 아니니까 메일보내는걸로 바꿨습니다.

**Comment by Bloodevil** [comment]
연대로 진행중 다음주 월요일까지 @lquaz님이 진행하시고 안되면 긴급논의가 필요 .

**Comment by Bloodevil** [comment]
@lqez  메일에 따르면 연대는 일요일날 건물출입을 봉쇄하기때문에 일요일 사용은 불가능하다고 합니다.

**Comment by Bloodevil** [comment]
누리꿈 스퀘어로 결정. 예약 완료. 5월에 관련서류 보내는 이슈가 생길예정.
