### ISSUE TITLE
CFP in English

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-2015#24]

**Comment by lqez** [comment]
@tebica wrote  https://docs.google.com/document/d/1k7MnzaykXnmhM6ZICt89QqeMRAaqKliNFm7fEmMCr5Y/edit.
Thanks!

**Comment by lqez** [comment]
http://www.pycon.kr/2015/index.en.html !

**Comment by tebica** [comment]
English proof reading 이 늦어지고 있네요... 조만간 마무리 하고  pull request 보내겠습니다. 혹시 이 것때문에 늦어지고 있는 다른 issue 가 있을까요?

**Comment by lqez** [comment]
그렇진 않은 것 같습니다.

**Comment by tebica** [comment]
원어민 Proof reading 하여 pull request 보내기 위하여 일단 reopen 합니다.

**Comment by tebica** [comment]
Proof reading 을 마쳤기에 닫습니다. push 완료.
