### ISSUE TITLE
파이콘 티셔츠 디자인 & 업체선정.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#28]
파이콘 티셔츠는 예산상 명당 만원으로 발표자 50벌, 자봉 30벌, 참가 700벌로 예상하고 있습니다.

총 800만원 규모로 예산잡고 있지만 넘을 것을 예상하고 있으니 넘어도 됩니다. 
* 디자인 비용을 따로 잡아야 합니다.
여름 티셔츠 반팔은 정해진 사항입니다.

급하진 않지만, 언젠간 무조건 해야하는 일이어서 이슈로 미리 넣어놓습니다.

**Comment by Bloodevil** [comment]
에코백도 있습니다.

**Comment by darjeeling** [comment]
* 티셔츠 3종류로
    * 일반 : 곤색
    * 자봉 : 코발트 
    * 발표자 : 차콜
* 소재는 보카시
* 단가는 대략 티셔츠가 칠천원 가량

**Comment by darjeeling** [comment]
* 발표자는 뒤에 스피커가 있어야함
* 스태프는 잘 보여야하는것이 주요

**Comment by devunt** [comment]
이거 막 제가 달아도 되는건지는 모르겠지만 작년 자봉용 티셔츠의 코발트색이 너무 절묘해 다른 행사나 아니면 그냥 밖에서 입고 다니기 힘들다는 의견이 있습니다. 눈에 잘 띄면서 평소에도 입고 다닐만한 색깔은 없을까요.

**Comment by darjeeling** [comment]
자원봉사자는 아무래도 행사에서 눈에 띄여야하기때문에 어쩔수 없는 색 배색입니다. 
안그러면 사람들이 등록데스크 같은 한곳에 몰려서 물어보기때문에 어쩔수가 없습니다.

**Comment by Bloodevil** [comment]
일반이 곤색이니 자원봉사자분들에게는 일반 티셔츠도 지급할수 있겠네요.

자원봉사자분들의 티셔츠의 색 고려는 다음과 같습니다. 
 - 잘보일것
 - 땀흘려도 민망하지 않을것 (...) 
 
아마 올해 색은 좀 낫지 않을까 싶습니다. :)

**Comment by corazzon** [comment]
발표자와 스탭은 설문으로 수량을 파악할 수 있으나 
일반 참여자에게 배부할 티셔츠의 사이즈별 수량이 필요합니다.

업체에서 제공하는 단체티셔츠는 길이가 짧기 때문에 1인치(2.5cm)당 500원 추가가 될 예정이며,
2인치 길이를 늘려 제작할 예정이라 단가가 1천원 더 올라갑니다.
또, 제작으로 인해 일반 단체티 제작기간에 비해 일주일~10일 정도가 더 소요 됩니다.

그리고 스탭의 경우 날씨관계로 양일 제공해야 하는 문제로 2장씩 제공할 예정입니다.

**Comment by Bloodevil** [comment]
코라존님으로 바꿉니다. 진행해주세요.

**Comment by Bloodevil** [comment]
deadline : 25일
zombieline : 28일.

티셔츠 출고기준. (당일날 누리꿈스퀘어로 배달되어도 됩니다.)

**Comment by scari** [comment]
Issue Raise. 마무리된 이슈로 알고 있지만 @corazzon 님 현재 결과만 업데이트 해주시고 이슈 닫아주세요.

**Comment by OuO** [comment]
티셔츠/에코백 은 잘 도착했고 지급 완료 되었으므로 닫습니다.

남은 수량에 대한 관리는 별도의 Ticket 으로 관리합니다.

@corazzon 님 수고하셨습니다
