### ISSUE TITLE
현수막

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#29]
현수막 필요함. 장소선정 끝나면 치수 재서 업체선정.

**Comment by Bloodevil** [comment]
http://nuri.nipa.kr/rt/
시설안내>광고물설치안내

**Comment by Bloodevil** [comment]
국제회의실 가로 8.5미터 세로는 상관 없음. 입니다.

**Comment by lqez** [comment]
디자인은 완료되었습니다.
업체 알아보겠습니다.

**Comment by lqez** [comment]
도착했습니다.
