### ISSUE TITLE
포스터

### ISSUE THREAD

**Issue by miyunim** [pythonkr/pyconkr-2015#30]
파이콘 코리아 2015 포스터 제작

디자인은 @lqez 님께서 맡아주심.

발표 장소 정해진 후 진행..

**Comment by miyunim** [comment]
사이즈 : A2 사이즈에 맞춰 디자인해주시면 됩니다.

**Comment by scari** [comment]
Issue Raise. 업데이트 부탁드립니다.

**Comment by lqez** [comment]
디자인 진행중이며 금요일까지 받을 예정입니다.

**Comment by lqez** [comment]
인쇄 완료되었습니다.
