### ISSUE TITLE
스탠드 배너

### ISSUE THREAD

**Issue by miyunim** [pythonkr/pyconkr-2015#31]
스탠드 배너 디자인은 동일하게 @lqez 님께서..

**Comment by miyunim** [comment]
사이즈: 60 X 180 cm

**Comment by Bloodevil** [comment]
。싸인 스탠드
    - 규격 : 가로 297mm x 세로 420mm (A3)
    - 위치 : 건물입구, 엘리베이터홀, 회의실 앞

http://nuri.nipa.kr/rt/
시설안내 > 광고물설치안내

**Comment by scari** [comment]
Issue Raise. 수량과 현재 상황 업데이트 부탁드립니다.

**Comment by lqez** [comment]
현수막과 같이 현재 배송중입니다.

**Comment by lqez** [comment]
도착했습니다.
