### ISSUE TITLE
라이트닝 토크 발표자 신청받기.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#32]
라이트닝토크 발표자 신청폼도 있어야 할 것 같습니다.

논의한후 적절하게 관리해주세요.

**Comment by Bloodevil** [comment]
@dahlia 님이 맡아서 진행해주시기 바랍니다. :)

**Comment by Bloodevil** [comment]
이거 끝났나요? 상태 업데이트 해주세요.

**Comment by lqez** [comment]
일반 세션과 같이 처리하고 있으니 #48 에 묶어서 보면 되겠습니다.
