### ISSUE TITLE
Flatpage urls

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-2015#35]
- [x] /about/coc/ -- 파이콘 성명서                                                               
 - [x] /about/contact/ -- 연락처                                                                    
 - [x] /about/pyconkr/ -- 파이콘 한국 2015                                                          
 - [x] /about/staff/ -- 준비위원회 및 자원봉사자                                                    
 - [x] /index/ -- index                                                                             
 - [ ] ~~/programs/bof/ -- BoF~~ -> Open Spaces 로 변경                                                                        
 - [x] /programs/cfp/ -- 발표자 모집                                                                
 - [ ] /programs/jobfair/ -- 취업 설명회 및 도서 판매                                               
 - [x] /programs/list/ -- 프로그램 목록                                                             
 - [x] /programs/schedule/ -- 세부 일정                                                             
 - [x] /programs/speakers/ -- 발표자                                                                
 - [x] /registration/ -- 등록 안내                                                                  
 - [ ] ~~/underconstruction/ -- 준비중~~                                                                
 - [x] /venue/hotels/ -- 숙박 안내                                                                  
 - [ ] ~~/venue/international/ --  해외 방문자 지원~~                                                   
 - [ ] ~~/venue/map/ -- 행사장 지도~~                                                                   
 - [x] /venue/restaurants/ -- 식사 안내                                                             
 - [x] /venue/transportation/ -- 교통편                                                             
 - [x] /venue/weather/ -- 날씨 안내

**Comment by Bloodevil** [comment]
일반인의 재정지원은 없어져서 해외 방문자 지원도 체크했습니다.

**Comment by lqez** [comment]
처리사항 정리하고 닫습니다.
수고하셨습니다.
