### ISSUE TITLE
Pycon 2015 보도자료 만들기

### ISSUE THREAD

**Issue by tebica** [pythonkr/pyconkr-2015#39]
일전에 H3나 Realm 릴리즈 준비할 때 보면 기자들이 컨퍼런스나 발표등에 대해서 더 쉽게 이해할 수 있도록 다양한 내용들을 보도자료로 준비해 주면 기사를 더 잘 써줍니다. copy & paste 기사를 위한 보도자료 보다는 Pycon 에 대해서 재미있는 사실들과 링크들을 모아놓은 자료를 기자들을 위해서 만드는 것이 좋겠습니다.

**Comment by Bloodevil** [comment]
괜찮은 링크들을 여기에 링크해서 현우님이 홈페이지 만드실때라던가 안에 내용 채워넣을때 참고하면 좋을 것 같습니다. (누구든지 관련있는 링크가 있으면 여기 comment로 정리해주세요.)

**Comment by Bloodevil** [comment]
직접 하고있는 것이 없어서 닫습니다. 만들 때 새로 이슈 만들어주세요.
