### ISSUE TITLE
세미나 2일 점심 및 뒷풀이 장소 예약.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#40]
2일간 전원 점심과 일부 사람들 뒷풀이 장소 예약해야함.

점심
- 케이터링
- 도시락
- 지정식당 쿠폰
- 세미나장 안에서 음식먹을 수 있는지
- 지하식당 공간

뒷풀이
- 뒷풀이 장소 인원 추출
- 인원확정되면 장소 알아보기 (가게를 통채로 빌리는게 편함)
- 메뉴
- 장소는 걸어서 10분 정도로

**Comment by Bloodevil** [comment]
음식관련 (식사 관련)	
 - 아침은 8시쯤 문열어줌, 더 별도로 일찍은 돈을 준비하면 가능함 : 12시 식사만 되면 됨.
장내 식사가능 여부	
- 장내 식사는 안됨 ( 간단한 다과, 커피 쿠키는 가능 도시락은 불가능, 지하에 상가에 이야기를 해서 하면 됨 )
- 보통 어떻게 해 왔는지 문의 부탁
푸드코드 대여 가능한지
- 푸드코트가 영업을 않하는데? 6월달에 영업을 않하고 공사중일수 있음 : 장소만 빌릴 수 있는지 문의해 보도록 하겠음.
- 근처의 식당을 이용하면 됨, 길건너가면 대각선맞은편에 kbs 미디어 센터가 있음 : 지하 식당도 가능. 몇군데를 컨텍할지, 아니면 돈을주고 먹게할지 등을 정해야 함. 

======
1안 : 푸드코트 장소만 빌리고 도시락 (1층에 본도시락인지 뭔지 있음) 배부가 가장 괜찮지 않을까 싶음. 근데 도시락 가게가 작아서 800개가 될지는 미지수 (물어봐야함)  안되더라도 근처에 가능한 도시락 가게는 얼마든지 있을 듯 함.

2안 : 푸드코트 빌리고 케이터링.

3안 : 쿠폰주고 지하식당 (몇군데 선택해서) 

======

푸드코트가 공사중일꺼라고 함. 문의 필요.

**Comment by iz4blue** [comment]
#88 에서 진행중인 것을 참고 부탁드립니다. #88 에서 리스트를 받아서 이 이슈에서 예약까지 하고 끝내야 할 것 같습니다.

**Comment by scari** [comment]
outdate issue. close.
