### ISSUE TITLE
Login with social authentication

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-2015#46]

**Comment by lqez** [comment]
by https://github.com/pennersr/django-allauth

**Comment by lqez** [comment]
https://github.com/pythonkr/pyconkr-2015/pull/57

**Comment by lqez** [comment]
But we have to talk about facebook apps. Currently, I can only create an app in my personal account.

**Comment by Bloodevil** [comment]
still personal account?

**Comment by lqez** [comment]
Yes, but we removed facebook login.
