### ISSUE TITLE
프로그램 북

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#47]
내용은 Google docs 에 따로 정리한다.

==프로그램 북을 만들 기 위해 정해야 할 것==
- 장소 : :ok: 
- 스피커 (스피커 소개, 사진)
- 세션 (세션 소개, 위치, 시간)
- 프로그램 시간표
- 와이파이 안내
- 스폰서 (스폰서 로고, 소개문구)
- 로비 잡페어 소개
-

**Comment by Bloodevil** [comment]
프로그램 북을 만들기 위해 요청해야 할 것들
- [ ] 스폰서 소개 (페이지 크기 및 예시)

**Comment by Bloodevil** [comment]
프로그램북 내용최종버전 정하는 날짜는 deadline, zombieline 보다 일주일은 성행되어야 할 것 같습니다.
필요한 내용 코멘트달아주세요.
프로그램북 출고기준
deadline : 25일
zombieline : 28일

**Comment by scari** [comment]
Issue Raise. 업데이트 부탁드립니다.

**Comment by lqez** [comment]
최종 인쇄 넘겼습니다. 금요일에 배송됩니다.
![img_7912](https://cloud.githubusercontent.com/assets/579366/9464646/8386f77a-4b60-11e5-8ce7-21fd5783e1bb.JPG)
