### ISSUE TITLE
참가자 양일 티켓 판매.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#50]
참가자 양일 티켓을 판매해야 합니다. 해야할 일들은 밑에 있습니다.
이 이슈는 적어도 5월 말까지 확정되어야 합니다.

* [x] 가격설정
* [x] 판매 갯수 확인
* [x] 결제 방법 선정 ( card, paypal 등 )
* [x] 카드 결제 업체 선정
* [ ] 홈페이지에 결제 시스템 연동
* [ ] 공지

**Comment by scari** [comment]
저도 서브로 같이 보겠습니다.

**Comment by Bloodevil** [comment]
deadline : 10일
zombieline : 16일

**Comment by Bloodevil** [comment]
티켓 마감기한 
다팔리거나 23일 자정까지.

**Comment by scari** [comment]
완판. 이슈 닫습니다. 환불/영수증 이슈가 있는데 이건 따로 열게요.
