### ISSUE TITLE
장소 비품 렌트.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#52]
==렌트할 사항들==
- [ ] 부스용 책상 15개
- [ ] 부스용 의자 30개 (부스용으로 약간 모자라게 빌리고, 모자란것은 오픈프론티어쪽에 의자를 빌릴 수 있다는 허락을 받음. 책상은 힘들 것 같다는 답변이 왔음.)

**Comment by Bloodevil** [comment]
http://www.seoule.co.kr/m_mall_detail.php?ps_ctid=38030000&ps_goid=978 이쪽.
행사용 의자/책상 세트는 책상1개에 의자 6개 세트로 4만원. (..원래 4만원 따로따로빌려도 ....)
책상만 빌리면 만원 접의식 의자는 개당 5천원

책상 종류는
W1830xD745xH755
W1560xD730xH715
W1230xD610xH740
3가지 1560정도면 될것 같음.

15개 의자 30개에 30만원 예상.

**Comment by darjeeling** [comment]
양일이고 + 상태가 스폰서용이라 깨끗해야할텐데 괜찬을까요?

**Comment by Bloodevil** [comment]
청결유무는 어디에서 빌려도 일단은 알수 없죠. 전화해서 물어봐야합니다. 아니면 금요일말 한번 닦거나 위에 전지를 깔아도 되구요. 

재활용센터지만 저건 대여용이고 재활용센터 가구나 전자제품이 그리 더럽진 않아요 센터에서 잔부 클리닝해서 나오기 때문에. 

 정 걱정되시면 하나 찾아서 url과 정보 올려주세요.

양일이니 *2가 되겠네요. 그리고 금요일 배송으로 하면 어떻게될지 모르니 전화해서 제대로 물어봐야할듯.

**Comment by iz4blue** [comment]
시트 에 정리 중
https://docs.google.com/spreadsheets/d/1MoO65HMYtEsO3gjtSIKg0ygTZtljGhB_hMsfYToCh5A

대여 가 예약이 끝나면 close 하겠습니다.

**Comment by scari** [comment]
키노트 (혹은 LT까지) 스트리밍을 위한 장비 대여도 예산 항목에 포함합니다. @tebica

**Comment by iz4blue** [comment]
대여는 끝나서 close 합니다.... 만!
의자 1개는 분실하여 새로운 이슈 열고 물품 파손 및 변상에 관한 이슈거리로 새로 등록합니다. #107
