### ISSUE TITLE
큰 시간표 공지사항보드를 만든다.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#53]
https://lh4.googleusercontent.com/-sqcqyfJuZEo/VTCft1rz5fI/AAAAAAAASsI/W0KlJERS0mg/w1024-h768-no/%EB%A9%94%EC%9A%B0%ED%81%B0%EA%B1%B0.png

위의 링크와 같은  큰 시간표 공지사항 보드를 만들어 봅시다.

- 만남의 장도 되고
- 시간표를 막판까지 고쳤을때 수정할수 있고, 빵꾸가 났을땐 직접 부셔서 덧대도 되고 (....) 

등등의 의미가 있을 것 같습니다.

**Comment by iz4blue** [comment]
@lqez 님 이건 OST 용 테이블 출력과 같이 하시는 거 맞죠?

**Comment by lqez** [comment]
@iz4blue 네 맞습니다. :)

**Comment by lqez** [comment]
인쇄 완료되었습니다.
