### ISSUE TITLE
Financial Aid

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#55]
관련 문의 확인 (googlegroups mail)
관련해서 논의한 후 결정 합시다. 문의가 들어왔으니 이번주  15년 4월 24일 안에 결정해서 답변주는게 바람직할 것 같네요.

**Comment by Bloodevil** [comment]
- [ ] 지원예산 확인
- [ ] 지원 범위 (발표자, 참가자(학생, 외국인, 내국인))
- [ ] 확정 후 공지.

**Comment by Bloodevil** [comment]
https://docs.google.com/document/d/1jQWjHSRo8I_TCrwQMua3n4aMOLmJX1C4oIvoAVnwtyQ

**Comment by Bloodevil** [comment]
*우선순위 1번*(스피커-키노트스피커 포함- )분들의 지원을 위한 메일발송을 진행합니다. 같은 문서의 밑에서 메일포멧 쓰도록 하겠습니다.
*우선순위 2번*인 학생참가자의 티켓 지원에 대한 공지도 함께 이루어지면 될 것 같습니다. 위의 조사가 끝나고 나면 예산의 일부가 묶이게 되니 그 나머지를 쓰면 됩니다. 이 공지도 같은 문서의 밑에 계속 추가합니다. 문서에서 의견 달아주세요.

현재 국내외 교통비/ 키노트스피커, 호텔비 다 해서 800만원이 잡혀있습니다

**Comment by scari** [comment]
안 하기로 결정. 학부생 이하 할인만 남겼습니다.
