### ISSUE TITLE
발표자(해외/지방) 호텔 예약.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#56]
* 상암 누리꿈 스퀘어 근처 호텔이나, 오기 쉬운 호텔과 딜을 한다.

5월 초에 발표자선정이 완료된 이후 진행가능 (5월 둘쨋주에 @hdkim41 님이 가실 예정)

**Comment by scari** [comment]
응답 마감이 25일이므로 그 다음에 예약 진행합니다. @tebica님이 스탠포트 호텔에 확인 완료 (8/22)

**Comment by tebica** [comment]
호텔조인이 가장 저렴(6.5만원+VAT), 한국어 커뮤니케이션 가능, 세금계산서 가능
http://www.hoteljoin.com/agent/index.php/resv/main/?hcode=1119
여기로 진행중

**Comment by tebica** [comment]
예약 확인되었고, 3분께 문자로 알려드렸고 3분다 확인답장을 주셨습니다.
[호텔조인]박민우님 2015-08-28 2박 150828-KR143701 스탠포드 호텔 예약완료
투숙객 이름이 등록되어있으므로 투숙객 이름대고 체크인 하면 됩니다.
조식포함 3명, 각 2박 (8/28 체크인)
