### ISSUE TITLE
스폰서 가이드라인.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#6]
스폰서 가이드라인이 필요함.

**Comment by Bloodevil** [comment]
되고있는거 google document 있었던 것 같은데 어디있나요.???

**Comment by tebica** [comment]
뭐 당연히 하시는 거겠지만, Sponsor Googld Doc directory 첨부합니다.
https://drive.google.com/drive/u/1/#folders/0BzZMptUH3U_ubnZfcGMyNDdUWnc/0BybJOTZiz2GiN3MxV2k0Rzg5UHM
@Bloodevil 스폰서 가이드라인은 어떤걸 이야기 하나요? 얼마를 내면 어떤 등급이다.. 이런거 인가요? 아니면 스폰서 전반적인 것들?

**Comment by Bloodevil** [comment]
스폰서 가이드라인은 어제 대충 나온 것 같습니다.
http://www.pycon.kr/2015/sponsor.html

스폰서 관리에 대한 것은 새로운 이슈로 열어도 될 것 같습니다. 어느정도 가이드가 정해졌으니 close 합니다. 혹시 더 정해야 할 것이 있으면 reopen해주시고, 스폰서 관리를 위한 이슈가 필요하시면 새로 열어주시기 바랍니다.
