### ISSUE TITLE
자원봉사자 모집 관련

### ISSUE THREAD

**Issue by sebuls** [pythonkr/pyconkr-2015#61]
http://www.pycon.kr/2015/about/staff/
일단 메일로 신청하면 신청자에게 추후 일정을 알려주는 건지
아니면 추후에 상세한 모집일정을 홈페이지를 통해 알려주는 건지
잘 모르겠습니다.
홈페이지에 명시해 주시면 좋겠습니다.

**Comment by OuO** [comment]
관련된 내용은 http://www.pycon.kr/2015/about/volunteer/ 를 참고하여주세요.
