### ISSUE TITLE
발표자 자료등록.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#64]
발표자분들의 자료등록에 관한 내용을 안내하고 피드백 받는다.

- 홈페이지에 발표자분들이 등록. : 등록 유도 메일안내가 있어야함. 발표 가이드라인과 함께 안내되면 좋을 것 같음.
- 발표자분들은 발표자 권한을 드리고 본인의 발표자료등록 및 내용 수정을 할 수 있게 한다.
- 직접 하지 않을 경우에는 요청드리고 업데이트 하는 식으로 (어떤 식으로든 이루어져야함.)

"@dahlia 님과 @lqez 님이 함께 해주시기 바랍니다. 발표자 중심의 일이라서 @dahlia 님께 어사인 드렸습니다."

**Comment by darjeeling** [comment]
* 발표자 가이드 작성
* 발표 관련 스케쥴 정리

**Comment by darjeeling** [comment]
* 발표자 재정지원 지원 스케쥴 ( financial aids 확정되면 확인 )
* 발표자료 최종 final out 스케쥴 - 2주전에 완료, 1주전이 진일정
* 프린트물에 나가는 자료 최종본 일정 ( 해당 스케쥴은 출력물 스케쥴에 연동됨 )
    * 발표자 정보 ( 프린트물에 나감 ), 사진, 약력등.. 홈페이지나 기타 링크등.. 자료..  -> 멀로 받지? -> 구글 폼은 안됨 수정이 안되니까.. -> 홈페이지??
    * 발표 러프한 레이아웃 ( 프린트 물에 나감 )

**Comment by darjeeling** [comment]
* 발표자 사전모임 시간 및 장소 확정 ( 6월 20일 )
* 장소 예약
* 재정지원에 대한 사항 안내
* 발표자 가이드 라인 안내 ( 5월 20일에 공지 )

**Comment by darjeeling** [comment]
* 티셔츠 사이즈 확인 필요

**Comment by Bloodevil** [comment]
발표자분들이 자료를 등록하도록 독촉해야할 것 같습니다. (당일까지 수저은 가능하더라도 대충의 뼈대는 미리 올려달라고 해야 합니다.) 독촉은 8월 7일, 12일, 14일, 20일 이렇게 비슷한 내용을 보내면 될 것 같습니다. (환기 필요) @corazzon 님께 부탁드리겠습니다. 
deadline : 15일
zombieline : 22일

**Comment by scari** [comment]
최종 자료 등록은 발표 직전에 세션 스태프와 함께 합니다. 현재 상태로는 그 외에는 모두 OOC. 클로즈합니다.
