### ISSUE TITLE
파이콘 한국 2015 사진 촬영 기사 확정

### ISSUE THREAD

**Issue by darjeeling** [pythonkr/pyconkr-2015#65]
사진 촬영기사는 4명정도로 진행
* 양일이므로..
* 신근우님 확정

**Comment by encyphered** [comment]
신근우입니다. 양일 모두 가능합니다.​

**Comment by OuO** [comment]
신근우님 외 2명 확정 되었습니다.

명단은 자원봉사자 명단 내 정리 되어있습니다.
