### ISSUE TITLE
발표자용 템플릿 애셋 준비

### ISSUE THREAD

**Issue by lqez** [pythonkr/pyconkr-2015#66]
* PyCon.KR 2015 로고 ??
* 메일 발송시에 "발표 포맷" 과 발표용 장비 가져올것인지 같이 메일로 발송

**Comment by darjeeling** [comment]
* 발표자에게 D-sub 출력임을 메일로도 알려줄것

**Comment by scari** [comment]
발표자 가이드에서 안내.
