### ISSUE TITLE
대회의실, 중회의실 의자갯수 확인 및 임대 방법 확인 ( 외부임대 or NIPA ? )

### ISSUE THREAD

**Issue by darjeeling** [pythonkr/pyconkr-2015#67]
기존에 대회의실, 중회의실에 의자가 있지만 예상되는 사람수에 모자라므로 아마 추가로 빌려야할듯함
확인이 필요하거나 추가로 임대가 필요할듯함

**Comment by lqez** [comment]
https://github.com/pythonkr/pyconkr-2015/issues/52 와 같은 곳에서 빌릴지 확인

**Comment by iz4blue** [comment]
외부임대 하며 시트에 업데이트 하면서 갱신중이여서 close 합니다.
https://docs.google.com/spreadsheets/d/1MoO65HMYtEsO3gjtSIKg0ygTZtljGhB_hMsfYToCh5A
