### ISSUE TITLE
휴게실, OST 용 소규모 회의실들용의 멀티탭 필요갯수 및 추가 의자 확인 및 임대 + 스폰서용 전원까지

### ISSUE THREAD

**Issue by darjeeling** [pythonkr/pyconkr-2015#69]
* 3층의 중회의실2 = 메인 휴실
* 3층의 소회의실,1,2,3 = OST 
* 4층의 소회의실 1,2, 중회의실 1  
* 4층의 여유공간에 놓을 의자 등등..
* 그리고 멀티탭

**Comment by darjeeling** [comment]
4층 사진 : https://drive.google.com/drive/folders/0BzZMptUH3U_ubnZfcGMyNDdUWnc/0BzZMptUH3U_uRngza2NZc3BXek0/0BybJOTZiz2GifkF2cV9QV0JzaDdrWldfdjdCZU9vYTktbWVTUWlKTEwtSDRfcE9LME9TUEk/0BwpH4x23I0k8fk1kR2x4QmR0NWU0UU9FRFF0cTB3TXNKaHdiQ2dOay15TEF3WjRSc3Z0ZEk

**Comment by darjeeling** [comment]
3층 사진 :
https://drive.google.com/drive/folders/0BzZMptUH3U_ubnZfcGMyNDdUWnc/0BzZMptUH3U_uRngza2NZc3BXek0/0BybJOTZiz2GifkF2cV9QV0JzaDdrWldfdjdCZU9vYTktbWVTUWlKTEwtSDRfcE9LME9TUEk/0BwpH4x23I0k8fk1kR2x4QmR0NWU0UU9FRFF0cTB3TXNKaHdiQ2dOay15TEF3WjRSc3Z0ZEk

**Comment by iz4blue** [comment]
OST = Open Space Tech (모여서 하고 싶은 이야기를 하는 곳)

**Comment by iz4blue** [comment]
차단봉 : 20개 이상

**Comment by iz4blue** [comment]
http://www.seoulrental.co.kr/ <- 이쪽 업체가 좀더 수량이나 규모가 더 커보임
단... 전원 케이블이나 콘센트 등은 이쪽도 보유하고 있지 않음
6권대 정도 알아보고 있는데 전원 케이블이 특이하게 제공되지 않음
이러다 직접 전원 케이블을 만들어 드려야 할지도? ....

**Comment by iz4blue** [comment]
각 콘센트마다 4kw 로 가능 <- 전력 담당자에게 다시 정확하게 확인하겠습니다.
스폰서 책상마다 노트북2개/모니터 2개 로 제한 <- 안내 메일을 @darjeeling 님 작성해주시기로 함
스폰서에게 제공되는 콘센트는 콘센트 2개 : 나머지 멀티탭등 추가 필요는 스폰서에서 해결

멀티탭 및 연장선은 필요한 제품으로 구매하기로 함
바닥 매설은 테이핑으로? 몰딩은 예상보다 비쌈. 테이핑으로 하였을때 끈적이는 것이 남는 것은?
대충 예산을 정해서 알려드리기로 함 : 대충 50~60쯤 될꺼 같음

**Comment by iz4blue** [comment]
소회의실 방에 10구 콘센트를 2개씩 배치할 예정임, 다음의 멀티탭을 고민할 생각임
http://item2.gmarket.co.kr/Item/detailview/Item.aspx?goodscode=405064795
연장선은 다음을 구매할 예정입니다.
http://item2.gmarket.co.kr/Item/detailview/Item.aspx?goodscode=439601594

**Comment by Bloodevil** [comment]
이미 도착해서 이슈 닫습니다.
