### ISSUE TITLE
OST 운영

### ISSUE THREAD

**Issue by darjeeling** [pythonkr/pyconkr-2015#70]

**Comment by iz4blue** [comment]
OST 설명들
http://egloos.zum.com/yuzi/v/1783326

'오픈 스페이스'란?, 최대 2000명까지 참여가 가능한 독특한 토론 프로세스입니다.

오픈 스페이스에서는 행사의 내용이나 진행자를 사전에 준비하지 않습니다. 대신에, '시간'과 '장소'등의 뼈대만을 준비합니다.그리고, 참여자들이 스스로 행사를 만들어 갑니다. 이렇게 함으로써, 참여자 주도의 정렬적인 행사가 됩니다.  

행사에는, '장소'와 '시간'으로 구성된 표가 준비되어 있습니다. 2차원적인 단순한 표입니다. 하나의 축이 시간대. 또 하나의 축은 장소입니다. 장소는 격식을 따지지 않습니다. 사람 수 정도의 의자만 있어도 좋습니다. 
 
행사를 개시하면 참여자들이 하나의 방에 모여 앉아서, 오픈 스페이스 방법에 대한 설명을 듣습니다. 그리고, 참여자가 스스로 세션을개최합니다. 세션은 누구나 개최할 수 있습니다. 세션은 개요와 타이틀을 '장소'와 '시간'으로 구성된 표에 공지하는 것 만으로충분합니다. 처음부터 모든 세션이 공지될 필요는 없습니다. 행사의 진행에 따라, 차례차례로 새로운 세션이 나올 것입니다.

표에 세션을 붙이면, 모두 이동을 시작합니다. 참여자는 언제라도 원할때 표에 새로운 세션을 붙일 수 있습니다. 세션 개최자는 언제라도 원하는 때에 자신의 세션을 이동할 수 있습니다.  

오픈 스페이스의 제 1법칙으로 '주체적 이동의 법칙(The Row of Two Feet )'이 있습니다. 이것은, 아무런 배울것이없고 공헌 또한 할 수 없다면, 더 생산적인 장소로 옮기는 것이 좋다는 것입니다. 즉, 세션을 옮겨다니는 것은 일반적이라는말입니다. 아무래도 참여하고 싶은세션이 겹친다면, 각각의 세션을 조금씩 함께 참여할 것도 방법이 됩니다. 많은 사람들은 이런것이 부자연스럽다고 생각합니다. 세션의 중간에 자리에서 일어나는 것은 실례라고 생각합니다. 그러나, 오픈 스페이스에 익숙하게되면, 옮겨다니는 것이 더 편하게 될 것입니다.

**Comment by iz4blue** [comment]
매우 자세히 나와 있네요. 굿 럭!
http://thechange.kr/changewaywiki/entry/오픈_스페이스_테크놀러지_(ost)

**Comment by iz4blue** [comment]
http://openspace.kr/oskorea/index.php?mid=notice1&document_srl=727682
영상 오글거림 주의!
https://www.youtube.com/watch?v=lWCRhylyVSs&feature=youtu.be

**Comment by OuO** [comment]
FIN!
