### ISSUE TITLE
Keynote 스트리밍 방법 및 가능성 확인

### ISSUE THREAD

**Issue by iz4blue** [pythonkr/pyconkr-2015#72]
국제 회의실 컨트롤 룸을 이용할 것인지?
직접 카메라로 찍어서 송출할 것인지?

방법과 누가할 것인지? 등등을 논의 해야함

이유는 : 국제회의실에 사람이 다 못들어감
우징님께 영상 인코더 장비를 대여하기로 이야기 되어 가고 있음
http://avertv.avermedia.com/product/ProductDetail.aspx?Id=585 <- 이것인 듯 싶음

**Comment by iz4blue** [comment]
국제 회의실에 있는 카메라는 CCTV 수준이라서 사용불가능 하다고 함
그래서 우리가 카메라, 삼각대 등을 이용해서 직접 송출해야함
영상 실시간 인코딩 장비는 우징님께 대여하기로 하였고, 네트워크 문제는 좀더 고민해야함

**Comment by Bloodevil** [comment]
우징님과 함께 진행해 주세요. (우징님 아이디가 안보여서 코멘트만 남깁니다.)

**Comment by iz4blue** [comment]
@Bloodevil 우징님께 관련 장비 받아왔고, 아직 테스트 전입니다.
일단 테스트해서 사용방법을 공유해야하는데, 아직 못해봤네요.
우징님이 이야기 하시기로는 youtube 중계를 이야기 하시긴 하셨습니다.

**Comment by iz4blue** [comment]
이번주 안으로 인코딩 장비 사용법 간단히 확인해서 공유하겠습니다.
다만 키노트 중계할 카메라, 스탠드, 노트북 등이 필요합니다.

**Comment by iz4blue** [comment]
우선 Mac 으로 간편하게 (대부분 Mac 을 쓰시니...) 할 수 있는 방법을 찾아 보았으나,
Mac 에서는 hangout 등에서 mac 용으로 ExtremeCap 장비를 연결할 수 있는 방법이 없는 듯 싶었습니다.
윈도우용 USB 3.0 이 있는 장비가 필요할 것으로 생각됩니다.

**Comment by iz4blue** [comment]
우징님께서 도와주시기로 하여 다음과 같이 정리되고 있습니다.
* 우징님께서 집 근처 노트북 대여점에서 노트북 대여를 진행해주시기로 하였음 ( 결제는 제가 대신 하면 될 것 같습니다. )
* 개인 스트리밍 장비(우징님) 및 개인 캠코더(김정환) 을 우징님께 전달해드렸습니다.
* 삼각대가 추가로 필요합니다.
* 랜선, 전원연결 등이 필요합니다.
* QOS 문제가 없는지 확인이 필요합니다.
* 가급적 29일 키노트 때 녹화를 부탁드리고, 30일 키노트 녹화가 어려우실 수 있으니 자원 봉사자 1분을 29일날 교육을 하면서 스트리밍을 부탁드렸습니다.

**Comment by iz4blue** [comment]
우징님이 토요일날 현도님과 함께 스트리밍을 어떻게 하는지 확인해주시고,
일요일날 키노트 중계를 해주시면 되겠습니다.

노트북은 2개 대여해서 중계되는 대회의실에서도 편하게 사용했으면 합니다.

**Comment by tebica** [comment]
우징님의 캡쳐장비 정보 입니다
http://gamerzone.avermedia.com/kr/game_capture/extremecap_u3
현장 유선 인터넷을 확인 중입니다.

**Comment by OuO** [comment]
행사 종료 되었으므로 종료합니다.
