### ISSUE TITLE
사이트에서 프로필을 수정하려고 하면 500 에러가 발생합니다.

### ISSUE THREAD

**Issue by corazzon** [pythonkr/pyconkr-2015#73]
프로필 수정 시 500오류 발생하는 문제 입니다.

**Comment by corazzon** [comment]
사이트에서 프로필 사진 등록이 파일이름이 한글이면 오류가 난다고 발표자 분이 회신을 주셨습니다.

**Comment by achimnol** [comment]
제가 해본 바로는, 파일이름이 한글이 아니어도 사진이 첨부된 상태이면 500 오류가 발생하고, clear 체크박스를 눌러서 사진을 제거하고 내용을 수정하면 다시 잘 됩니다.

**Comment by lqez** [comment]
@achimnol 님의 제보가 정확합니다. 이미지 크기(dimension)과 파일 크기 처리하는 부분에 예외 처리가 없었습니다.
이용에 불편을 드려 죄송합니다.

**Comment by lqez** [comment]
`_size` 값 문제를 우선 우회처리했습니다.
https://github.com/pythonkr/pyconkr-2015/commit/6b70a30846b02df9787a67d42194c4f8a9e42bd8
