### ISSUE TITLE
프로필 수정 후 자기소개 글이 보이지 않습니다.

### ISSUE THREAD

**Issue by achimnol** [pythonkr/pyconkr-2015#74]
아래 #73 이슈 관련해서 제 프로필을 고치면서 알게 된 것인데, 자기소개글을 입력해도 로그인 세션이 살아있는 브라우저에서만 자기소개 내용이 출력되고 그렇지 않은 브라우저에서는 보이지 않습니다. 사진과 소셜링크는 양쪽 모두 잘 나옵니다.
(이게 제것만 그런 것인지도 모르겠습니다. 배권한님이 수동으로 이멜 주소 연동시켜주셨는데 혹시 DB 쪽에 뭔가 필드 업데이트가 빠져있는 거 아닌가 싶기도 합니다.)

**Comment by lqez** [comment]
django-modeltranslation 을 이용해서 모델을 번역하고 있는데, English 로 세션이 열린 상태에서 데이터를 입력하셔서, en 필드에 값이 입력되었는데, 다른 언어로 열린 세션에서는 ko 필드 (비어있는)를 읽고 있어서 발생한 문제입니다. 

ko 필드에 값이 있고, en 필드에 값이 없을 때는 fallback 이 잘 되는데, 반대로는 잘 안되는 것이 문제이므로 수정해보겠습니다.

**Comment by lqez** [comment]
수정되었습니다.
https://github.com/pythonkr/pyconkr-2015/commit/a3f6b908ccc52fec3ba97fdfecfe9b9f823937dc
