### ISSUE TITLE
무선랜 사용법 문의

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#75]
누리꿈스퀘어에 무선랜 사용법 문의.

1. 일반 참가자용 무선랜 사용과 스폰서용 무선랜, 그리고 스태프용 무선랜을 따로 구분할 수 있는지. -적어도 스폰서용은 따로 구분되었으면 좋겠습니다.
2. 사용법 프로그램북에 실어야 한다면 미리 인쇄가 되어야 함.

**Comment by iz4blue** [comment]
그때 무료 WIFI 가 제공된다고 들었는데 오늘 막상 와보니 상황이 다릅니다.
NURI_GUEST 가 암호를 요구하는 인증형 WIFI 입니다.
이 부분 월요일날 전화해서 확인하도록 하겠습니다.

![screen shot 2015-06-06 at 9 46 47 am](https://cloud.githubusercontent.com/assets/979297/8017464/3100f082-0c31-11e5-9afc-1b5a48b26f0e.png)
![screen shot 2015-06-06 at 9 48 40 am](https://cloud.githubusercontent.com/assets/979297/8017466/3e1c3506-0c31-11e5-81f0-85521921e92f.png)

**Comment by Bloodevil** [comment]
네 저는 이 아이디 패스워드를 제공해주는것으로 알고 있었습니다. 즉, 대관을 하면 아이디 패스워드를 무료로 알려준다고 하는걸로 들었고, 이 아이디 패스워드를 두개로 나눠 받을 수 있는지, 몇명까지 커버 되는지가 궁금합니다.

**Comment by Bloodevil** [comment]
@iz4blue 님의 slack log 첨부합니다.
====
네트워크 구조는 매우 많이 받을 수 있도록 셋팅이 되어 있는 것으로 보아 무난할 것 같습니다. 
(실제 가능한지는 다시 확인후 알리겠습니다.)
강연자 용으로는 유선랜을 신청하여 wifi 를 제공하도록 하겠습니다. (그래봐야 3개 *2틀 이니)
====

유선랜 신청과 계정정보 등의 정보등을 google docs에 올리시면 close 해주세요.
deadline : 24일
zombieline : 27일

**Comment by iz4blue** [comment]
* QOS 문제 확인 필요
* 유선랜 4개 2일 신청 예정 : 대회의실 keynote 중계용, 각 강의실용
* wifi 무료 제공은 255.255.252.0 의 bitmask 로 되어 있음 : 이론상 1022 개의 IP 가 할당될 수 있음
* 무선 공유기 3개 확보 필요
* 접속 ID / PASS 는 공개된 곳에 노출은 일단 보류 (github 에만)

좀더 자세한 이야기는 무선 담당자와 연락후 다시 적도록 하겠습니다.
