### ISSUE TITLE
발표 가이드라인.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#8]

**Comment by Bloodevil** [comment]
발표 가이드라인은 발표자가 선정되면 뿌립니다.

**Comment by tebica** [comment]
제 경험으로는 보통 발표자 템플릿 정도를 공유하고.. 그것도 잘 사용되는 편은 아니던데,
발표 템플릿을 제공하려고 하는건 아니지요?
로고 가이드라인 과 현우님이 작성하신 "파이콘 이름 작성 방안" 정도면 되지 않을까요?
https://docs.google.com/document/d/1Tlwkef3tthINpooZiJkzBbKc5C70M7qtSKs-B1QcXtQ/edit
로고 가이드라인은.. "배경이 흰색이어야 한다" 이정도?

**Comment by Bloodevil** [comment]
넵 그런 요소들이 정리를 한거랑 안한거랑 달라서 한장짜리라도 메일로 공지가 필요할 것 같습니다. :)
로고도 갔다쓰세요 보다는 패키지로 제공하면 좋을 것 같구요. 작년에도 그런 문의가 있었습니다.

**Comment by Bloodevil** [comment]
https://docs.google.com/document/d/1r4b5zbSAgRGOayjlK9wFbKGbCu1QYM4Ac62EkgHszNs/edit#heading=h.jzmo5bujf3nn

**Comment by dahlia** [comment]
뒤늦게 살펴보게 되서 죄송합니다.

위에 링크된 문서 내용은 주로 발표자를 선정하는 기준에 관한 것이고, 참고할 것이 있긴 한데, 발표 가이드라인은 우선 뭔가 정해져야 할까요? 지금 뭔가 시작해보려니 궁금한 것들이 많은데요, 우선 이 가이드라인은 최종적으로 발표자로 확정된 분들을 대상으로 하는 것일지, 아니면 1차 선정만 되어도 보내드려야 하는 것인지, 아니면 발표자 신청하신 모든 분들께 보내드려야 할지 궁금합니다. 그에 따라 다뤄야 할 내용이 달라질 것 같습니다.

**Comment by dahlia** [comment]
만약 이 가이드라인이 최종 선정된 발표자를 대상으로 한다면, 위에 링크된 발표자 선정 기준의 내용은 많은 부분 발표 가이드라인에는 넣을 필요가 없어질 것 같고요 (왜냐면 이미 그러한 기준을 통과하는 분들만 받을 것이기 때문에?). 그냥 선정과 상관 없이 발표자 지원하신 분들 모두를 대상으로 한다면 발표자 선정 기준에서 발표 내용에 관련한 부분들을 정리해서 문서를 만드는 정도로 마무리할 수 있을 것 같습니다.

**Comment by dahlia** [comment]
혹시 [발표자 준비사항][1] 문서가 발표 가이드라인 작업 초안인가요? 아니면 발표 가이드라인과 발표자 준비사항 문서는 별개인지…

[1]: https://docs.google.com/document/d/1OmBHGuTMrlt1v0UMy3Njce4MsN_V0laG28agwYqmklU/edit#heading=h.qp2wd3kli4v1

**Comment by Bloodevil** [comment]
그러네요 제가 쓴 링크는 이슈에 맞지 않고 발표자 준비사항 문서가 맞습니다.  (삭제하였습니다.)
예전에 @darjeeling 님이 넥슨발표자용 발표자 가이드라인을 올려주신게 있었던 것 같은데 거기에 로고 사용, 추천 바탕색,(해당 행사장에서 잘 안보이는 색과 잘 보이는 색을 추천했음) 행사의 톤앤매너 같은 걸 정리했던게 있더라구요.

**Comment by dahlia** [comment]
@darjeeling 혹시 넥슨 발표자용 발표 가이드라인 구할 수 있을까요?

**Comment by miyunim** [comment]
[2014년도 N모사 발표 가이드라인](https://drive.google.com/folderview?id=0ByTDpU6rgnjZfnBtR0d0dFdzVWpCZERxYUs5OFpWQlVoSEgyWTdnZ0d6TzdTd3dsWTN1M0U&usp=sharing) 입니다.
이게 맞는진 모르겠지만.. 일단 공유폴더에 업로드해두었습니다.

**Comment by corazzon** [comment]
감사합니다. :)

**Comment by Bloodevil** [comment]
코라존님 발표 가이드라인 간략하게 정리해주세요. 필수요소는 맨 처음 페이지 디자인과 파이콘 2015 로고 파일정도가 아닐까 싶습니다. 진행 부탁드려요.

**Comment by Bloodevil** [comment]
#66 이것과 비슷하여 이쪽 이슈는 닫습니다. relate를 위해 이슈 걸어놓습니다.
