### ISSUE TITLE
Restart!

### ISSUE THREAD

**Issue by scari** [pythonkr/pyconkr-2015#80]
핀 포스트로 걸어두기엔 양이 좀 많아서 일단 여기다 몰아둡니다. 이미 확인했던 이슈들이 대부분이지만 7월말 ~ 8월초가 휴가기간이라 영향이 있지 않을까 생각되서 remind한다는 기분으로 한번 더 확인하고 갔으면 좋겠습니다.

- 추가 발표자 컨택 @scari
 - 발표자 사전 모임 일정 및 장소 섭외 @scari

- 홈페이지 일정 업데이트 및 프로그램/발표자 목록 정리 @lqez 
 - SNS 홍보 @Bloodevil @lexifdev 

- 자봉 일정 확인 @OuO 
 - 스탭 사전 모임 일정 및 장소 섭외 @OuO 

- 티셔츠 업체 일정 확인 @corazzon 

- 스티커 업체 확인 @Bloodevil 

- 스폰서 관련 사항 (부스 배치 및 부스 활동 내용 확인, 진행 상황 공유 등) @darjeeling

**Comment by OuO** [comment]
자봉 일정 확인은 #79  에서 관리중입니다.

**Comment by Bloodevil** [comment]
분배했습니다.
