### ISSUE TITLE
img.media-speakerect 이미지가 정사각형이 아닌 경우 눌려보이는 문제

### ISSUE THREAD

**Issue by yoloseem** [pythonkr/pyconkr-2015#81]
`media-speakerect` 클래스 css 먹힌 `img` 태그에 정사각형이 아닌 이미지가 들어가는 경우 crop 되는 대신에 눌려보이고 있습니다.

**Comment by iz4blue** [comment]
아하 무슨 말인지 이해가 됩니다.
http://www.pycon.kr/2015/programs/speakers/ 에서 보시면
예를 들어 하용호님 그림은 크롭이 되는게 아니라 상하 비율이 적게 되서 보이네요. (가장 비율이 깨지는 것이여서 예시를 듭니다.)

**Comment by lqez** [comment]
Fixed in https://github.com/pythonkr/pyconkr-2015/commit/5ee9e992c43a5946abce0b33accc3e8a1e67edeb
Thank you for reporting.
