### ISSUE TITLE
스탭, 발표자 사전모임 일정잡고 장소 섭외하기.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#82]
자원봉사자, 발표자 사전모임 일정 잡고, 공지 돌리고, 장소 섭외하기.

**Comment by Bloodevil** [comment]
@OuO 자원봉사자
@scari  발표자

같은날 같은 장소에서 해도 되고 (기본 공지 내용이 같으므로) 따로해도 됩니다.

**Comment by Bloodevil** [comment]
발표자는 2주전, 자원봉사자는 pyjog나오라고 유도할 예정입니다.

**Comment by scari** [comment]
같은 날(8/14 금요일 저녁) 하는걸로 가닥 잡고 장소 섭외 진행합니다.

**Comment by scari** [comment]
8/14일 19시부터 강남역 Naver D2 Factory.
발표자/자원봉사자/스폰서 안내 메일 발송했습니다.
