### ISSUE TITLE
홈페이지 내용 업데이트.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#84]
프로그램/발표자 목록 업데이트
일정 업데이트

**Comment by scari** [comment]
Issue Raise!

최종 확정 발표자 명단은 동보메일용으로 뽑아뒀던 리스트를 참고하시면 되겠습니다.
https://docs.google.com/spreadsheets/d/1A0UQDavRUeZ6io4z9-IsPQfBSZFNhFDqzN80HO1yjHk/edit#gid=0

여기에 백업 멤버 두 분 추가입니다.

**Comment by scari** [comment]
완료
