### ISSUE TITLE
스티커 제작.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#87]
디자인 부터 시작. 그후에 업체를 알아봐야 함.

**Comment by Bloodevil** [comment]
deadline : 15일
zombieline : 25일

**Comment by lqez** [comment]
:eyes: got it

**Comment by Bloodevil** [comment]
https://www.stickermule.com/products/rounded-corner-stickers 에서 주문.

**Comment by Bloodevil** [comment]
주문/디자인 완료
https://slack-imgs.com/?url=https%3A%2F%2Fartisan-production.s3.amazonaws.com%2Fartwork_revisions%2F198316%2Foriginal%2F490992.png%3FAWSAccessKeyId%3DAKIAIRHCXA5ES7K6S5VA%26Expires%3D1439428830%26Signature%3DYvEfqng5lSBkNXRpWrFkoVKZ7dE%253D&width=261&height=97
https://slack-imgs.com/?url=https%3A%2F%2Fartisan-production.s3.amazonaws.com%2Fartwork_revisions%2F198365%2Foriginal%2F490994.png%3FAWSAccessKeyId%3DAKIAIRHCXA5ES7K6S5VA%26Expires%3D1439428855%26Signature%3DQPZBHYwq7GdvksHjBMsbmZ6fO8U%253D&width=209&height=210

배송온것 확인하고 이슈 닫을 예정입니다.

**Comment by Bloodevil** [comment]
배송중이고 24일 배송완료될 예정입니다.

**Comment by Bloodevil** [comment]
배송완료. 끗.
