### ISSUE TITLE
주변 식당 연락처, 이름, 위치파악

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#88]
누리꿈스퀘어 근처 식당, 식당 연라거, 이름, 위치파악해서 홈페이지 업데이트.

**Comment by Bloodevil** [comment]
deadline :  22일
zombieline : 28일

**Comment by iz4blue** [comment]
식당 리스트 정리 URL 입니다.
https://docs.google.com/spreadsheets/d/1CjatrMebUSNe7bGnzggk-naxD5de09zF7m_f7vFdFFo

**Comment by Bloodevil** [comment]
@hdkim41 정환님이 정리해주신 docs에 실제 영업하는지, 좌석수 몇개인지 확인해서 채워주세요. 시트 채우는건 deadline 15일 입니다. 22일까지는 홈페이지에 업데이트해야하는 기간이니까 참고해주세요.

미리감사 'ㅁ' ㅋ

**Comment by iz4blue** [comment]
@scari 님 나머지 연락 추가로 확인 부탁드립니다.

**Comment by scari** [comment]
@hdkim41 님이 모두 확인해주셨습니다. 클로즈합니다.
