### ISSUE TITLE
8월 10일 스폰서 공지에 필요한 내용.

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#89]
8월 10일에 나갈 스폰서 공지 내용 정리합니다. 더 필요한건 이쪽에 추가해주시고 공지는 다즐님께 할당할께요.

1. 일요일 스폰서 물품은 5시 30분부터 정리합니다. - 양해부탁드립니다. @iz4blue 
2. 프로그램북 진행상황 @lqez 
3. 확정 시간표 공지 @scari 
4. 무선랜/유선랜 사용에 관한 공지. @iz4blue 

 + 중간 모임은 자원봉사자, 발표자들 모이는데 그것에 관한 정보도 한번 환기시켜주면 괜찮을 것 같네요.
... 못할것 같다 하는 부분은 빼고 필요한 부분은 더 정리해주세요.

**Comment by iz4blue** [comment]
스폰서 무선랜이 있군요. 이건 가급적 우리가 인포데스크에 AP 를 설치해서 따로 제공하는게 맞을 것 같습니다.
이쪽 담당자도 대규모 인원이 한꺼번에 붙는 것을 완벽하게 보장할 수는 없는 상황으로 이야기 하는 중이라,
가장 확실한 방법인 유선랜 + AP 로 반드시 인터넷이 되어야 하는 분들은 그렇게 제공하는게 맞는 것 같습니다.
AP 가 확보될 수 있는 수량을 좀 찾아봐야겠네요.

**Comment by Bloodevil** [comment]
+1

**Comment by woojing** [comment]
성능좋은건 아니고 그냥 저가형 가정용공유기 하나 집에 남는거 있어요.

**Comment by lexifdev** [comment]
저도 저렴한 공유기 하나 남는거 있습니다.

**Comment by Bloodevil** [comment]
https://docs.google.com/document/d/1CeaxnbZLtql5_QdCMwtPGQ142pVbtUT3HFXR1BwSqL4/edit 문서에 추가해 주세요. 최종 이메일 형식 입니다. 보내고 나면 이 이슈는 닫습니다.

deadline : 10일
zombieline : 12일

**Comment by Bloodevil** [comment]
끝나서 닫습니다.
