### ISSUE TITLE
Call for proposal

### ISSUE THREAD

**Issue by Bloodevil** [pythonkr/pyconkr-2015#9]
- minimum guide line.
- 발표자가 준비되었는지를 미리 좀 보는 기회가 있어야 함.
- 주제는 없음.
- 기간을 길게 주기.

- 파이썬 냄새가 나야함.
- 스폰서 세션도 일단 받는다.
- 난이도와 대상청중 표시해주세요.

**Comment by tebica** [comment]
Call for proposal Pycon APAC 2014
https://mail.python.org/pipermail/conferences/2014-January/000546.html

**Comment by lqez** [comment]
@tebica 이거 마무리 되시면 저한테 할당해주시면 감사드리겠습니다.

**Comment by lqez** [comment]
2015 CFP https://docs.google.com/document/d/1MK7d-C94EHh-OaSNCemNYvuo1P7OhPjKej2XZHSBf4s

**Comment by lqez** [comment]
홈페이지에 등록되면 닫겠습니다.

**Comment by tebica** [comment]
@lqez 아름다운 홈페이지에 등록되었으므로 닫아도 될 것 같습니다. 그냥 닫을까.. 하나다 noti 드립니다~

**Comment by iz4blue** [comment]
@tebica 님의 의견에 찬성 1표요~ ^^a (정말 페이지가 아름다움... 우웅~ 능력도 부럽고 감각도 부럽고...)
참고로 pycon.kr 페이지가 3gs 에서도 잘 나옴을 확인했습니다.

**Comment by lqez** [comment]
@tebica 영문 CFP 작성 완료되시면 저한테 돌려주세요. 감사합니다.

**Comment by Bloodevil** [comment]
@tebica #24 이슈가 있으므로 이쪽은 닫습니다. #24 CFP in english로 이슈레이징 해주세요.
