### ISSUE TITLE
누리꿈 장소 대관 추가 사항들 포함 재 계약

### ISSUE THREAD

**Issue by iz4blue** [pythonkr/pyconkr-2015#93]
- [x] 유선랜 4개 : 국제 회의실, 로비, 대회의실, 중 회의실 1 무선랜 먹통 사태를 대비해서 임대 예약
- [x] 정수기 5개 : 3층 국제 회의실 문 옆에 2개, , 4층 밖에 1개, 3층 로비 1개 추가, 국제 회의실 스피커 휴개실 중앙에 1개
- [x] 정수기 강의장 내부 4개 : 4층 대회의실 1개, 3층 중회의실 1 1개, 3층 중회의실 2 1개, 4층 중회의실 1개
- [x] 물통 20개 : 기본 9개 + 10개

미 결정
- [ ] 추가로 대여한 소 회의실 및 3층 중회의실 2, 4층 중회의실 에도 빔을 대여할지?

계속 갱신하겠습니다.

**Comment by Bloodevil** [comment]
정수기는 이미 9개가 구비되어 있습니다. (대관 안에 포함되어 있음.) 
https://docs.google.com/drawings/u/1/d/11XlLVf85jiLn9FZd-sJ1aHyWM1DGvFA6S6V1Or4sYPg/edit?usp=drive_web

물통은 추가로 문의 하겠습니다.
빔은 일단 문의하지 않습니다.

**Comment by Bloodevil** [comment]
1.     유선랜 (개당 1만원)
2.     정수기 (개당 5,000원)
3.     추가 마이크 (무료), (회의실에 따라 보유여부와 수량이 각각 다름!! 어디서 추가 사용 할 지를 자세히 알려주시면 다시 안내 드리겠습니다.)
4.     [추가정보] 델리게이션마이크 (회의용 마이크, 2만원, 회의실에 따라 보유여부와 수량이 각각 다름!! )

유선랜 4개 정수기 10통 추가신청하겠습니다.

추가마이크는 국제회의실, 2개 대회의실 1개 중회의실 1개(총 2개) 5개 더 신청하겠습니다.
빔은 추가로 알려주세요.

**Comment by Bloodevil** [comment]
정수기 물통 답변 : 
"정수기는 다시 확인해 보니, 1개 배치될때 요청하면 2개정도씩 여분물통을 준다고 합니다.
추가비용은 안들어가도 되구요."

유선랜은 위치를 문의받았는데 위치상으로 국제회의실 뒷편이 좋을 것 같습니다. 로비에 가능하냐고는 따로 물어보겠습니다.

**Comment by Bloodevil** [comment]
빔이 필요하면 새로운 이슈로 파고 이외의 것들은 협의가 거의 끝나서 close합니다.
